### ISSUE TITLE
Issues with non founding members preview list

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream-org#289]
Two questions about this section

![Screenshot 2021-03-18 at 18 53 55](https://user-images.githubusercontent.com/437292/111673704-88781e00-881b-11eb-89c4-4956c7d2ccf1.png)

1. Why do the membership avatars not get displayed here? It also not happen on the full ranking by the way.
2. The link goes to the wrong full ranking, it goes to the founding member overview.

**Comment by DzhideX** [comment]
1. The data for all of these comes from the `founding-members` repo under `data/fm-info.json`. As it currently stands non-fm members don't have any avatars there. I could technically make a request for those avatars from the testnet but that would astronomically shoot-up the loading times for non-fm members. I think the best solution, if we really want their testnet avatars is to somehow manually add them to the json itself? Would that be possible @bwhm?

2. This has been fixed in the PR i just mentioned!

**Comment by bedeho** [comment]
1. Why not just load the page as you are doing now, but then do async in place loading of individual handles as the next step? The current hundreds of grey circles just make no sense.

**Comment by DzhideX** [comment]
Agreed and it really doesn't make sense to add them manually to the JSON. Will get on it asap!
