### ISSUE TITLE
Weird animation artefact on landing page title

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream-org#537]
This is on Firefox, and strangely, it only occurs on one of my two screens on the same machine.

![Screenshot 2022-08-12 at 09 33 50](https://user-images.githubusercontent.com/437292/184306828-b30bd046-780c-4bbc-9ca7-f5d2f1c12a9c.png)

**Comment by kdembler** [comment]
I think this is a Firefox bug, not sure if anything can be done about it. I have seen similar gray rectangle on Atlas once, but it was a browser rendering artifact

**Comment by kdembler** [comment]
Update: after heroic investigation from @drillprop our conclusion is that this is most likely caused by the `filter` CSS property applied to some images, both in Atlas YPP Landing Page and joystream.org:
![image](https://user-images.githubusercontent.com/12646744/190088993-b4f3d45e-081f-4160-bf2d-8a69263db0b3.png)

We had that same `filter` applied in Atlas and we think that caused the rectangle and also caused other performance issues on the page. Removing it, fixed those

**Comment by DzhideX** [comment]
Thank you for finding the source of the problem @drillprop ! I also submitted a [bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1787132) to mozilla so hopefully they get around fixing the problem eventually :)

In the meantime I'll just remove the drop-shadow from the illustration.
