### ISSUE TITLE
Tweak Exchange Section of Landing Page

### ISSUE THREAD

**Issue by bedeho** [Joystream/joystream-org#776]
# Background

Current version is designed to look something like this

![Screenshot 2024-01-09 at 21 58 41](https://github.com/Joystream/joystream-org/assets/437292/7bb9852c-c6e9-41c6-9819-d7ae4269f7ea)

This is no longer the ideal design. As we now will have a dedicated buy experience, a lot of space is being wasted in this design in order to help the user pick an exchange, and it ends up doing a poor job compared to what the dedicated buy page will do, but on the flip side we end up using a lot of space, and dealing very poorly with the case when we have north of 2-3 exchanges, which is already the case. 

# Proposal

Lets do a design which just focuses on identifying the set of exchanges in a space efficient way, and for each one we want to know
- **24h Volume** (most important): The dollar value of the 24 hour trading volume on this exchange, typically a dollar number from $10,000 to $10,000,000
- **+2% Depth** (a bit less important): The dollar amount on within 2% of mid price on sell side, typically a dollar number from $100 to $100,000
- **-2% Depth** (a bit less important):  The dollar amount on within 2% of mid price on buy side, typically a dollar number from $100 to $100,000

We also replace the per exchange buy button, with a single call to action button which helps the user buy joy by linking to the buying page we will have in the future. Lets have a design where we an release a version for the dashboard where this buy call-to-action is not present, so we can launch the dashboard without having to have completed the buy page at the same time, as that may cause additional delay.

**Comment by msmadeline** [comment]
Hey @bedeho I implemented your feedback.✅

- I added another proposal on how to display data in the exchange cards. I decreased the prominence of the +2% and -2% Depth data so when you slightly squint your eyes you can see that the first data that is noticeable is the Volume data, then the name of the exchange and then the depth data is the last. I also added the real data so that you can see how it will be displayed in the real world. 
link: https://www.figma.com/file/SW6P9qk1RLha7nAfUk7ONo/Dashboard-explorations?type=design&node-id=1807-11903&mode=design&t=hMr7jXOlC7n9BGRn-4

- I proposed 2 solutions of how to display the cards when there is for example 5,6,7 of them and not enough to make 2 rows.
 
Adding "placeholders cards" - https://www.figma.com/file/SW6P9qk1RLha7nAfUk7ONo/Dashboard-explorations?type=design&node-id=1808-15093&mode=design&t=hMr7jXOlC7n9BGRn-4

Aligning to the left - https://www.figma.com/file/SW6P9qk1RLha7nAfUk7ONo/Dashboard-explorations?type=design&node-id=1809-18484&mode=design&t=hMr7jXOlC7n9BGRn-4
In my opinion aligning them to the left is a better approach as it will not make user confused 

- I also made demonstration on how it would look like on low resolutions (XXS. XS. SM) both deafut and expanded 
link https://www.figma.com/file/SW6P9qk1RLha7nAfUk7ONo/Dashboard-explorations?type=design&node-id=1809-24990&mode=design&t=hMr7jXOlC7n9BGRn-4

**Comment by bedeho** [comment]
I think this all looks brilliant, lets add place holder cards,looks great.
